spring:
  #激活环境
  profiles:
    active: dev

#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:cn/allams/hkjforum/mapper/xml/*.xml


